INSERT INTO bookmarks (title, url, rating, description)
values 
('Test', 'www.test1.com', 5, 'meh'),
('Test1', 'www.test2.com', 5, 'meh'),
('Test2', 'www.test3.com', 5, 'meh'),
('Test3', 'www.test4.com', 5, 'meh'),
('Test4', 'www.test5.com', 5, 'meh'),
('Test5', 'www.test6.com', 5, 'meh'),
('Test6', 'www.test7.com', 5, 'meh'),
('Test7', 'www.test8.com', 5, 'meh'),
('Test8', 'www.test9.com', 5, 'meh'),
('Test9', 'www.test10.com', 5, 'meh'),
('Test10', 'www.test11.com', 5, 'meh'),
('Test11', 'www.test12.com', 5, 'meh'),
('Test12', 'www.test13.com', 5, 'meh'),
('Test13', 'www.test14.com', 5, 'meh'),
('Test14', 'www.test15.com', 5, 'meh'),
('Test15', 'www.test16.com', 5, 'meh'),
('Test16', 'www.test17.com', 5, 'meh'),
('Test17', 'www.test18.com', 5, 'meh'),
('Test18', 'www.test19.com', 5, 'meh'),
('Test19', 'www.test20.com', 5, 'meh'),
('Test20', 'www.test21.com', 5, 'meh')